//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Location", Namespace="http://schemas.datacontract.org/2004/07/velibPlanner")]
    [System.SerializableAttribute()]
    public partial class Location : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double latitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double longitudeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double latitude {
            get {
                return this.latitudeField;
            }
            set {
                if ((this.latitudeField.Equals(value) != true)) {
                    this.latitudeField = value;
                    this.RaisePropertyChanged("latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double longitude {
            get {
                return this.longitudeField;
            }
            set {
                if ((this.longitudeField.Equals(value) != true)) {
                    this.longitudeField = value;
                    this.RaisePropertyChanged("longitude");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Route", Namespace="http://schemas.datacontract.org/2004/07/velibPlanner")]
    [System.SerializableAttribute()]
    public partial class Route : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double durationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] durationsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.ServiceReference1.Segment[] segmentsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double duration {
            get {
                return this.durationField;
            }
            set {
                if ((this.durationField.Equals(value) != true)) {
                    this.durationField = value;
                    this.RaisePropertyChanged("duration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] durations {
            get {
                return this.durationsField;
            }
            set {
                if ((object.ReferenceEquals(this.durationsField, value) != true)) {
                    this.durationsField = value;
                    this.RaisePropertyChanged("durations");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.ServiceReference1.Segment[] segments {
            get {
                return this.segmentsField;
            }
            set {
                if ((object.ReferenceEquals(this.segmentsField, value) != true)) {
                    this.segmentsField = value;
                    this.RaisePropertyChanged("segments");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Segment", Namespace="http://schemas.datacontract.org/2004/07/velibPlanner.entities")]
    [System.SerializableAttribute()]
    public partial class Segment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.ServiceReference1.Location destinationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double distanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double durationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string instructionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.ServiceReference1.Location sourceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string transportModeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.ServiceReference1.Location destination {
            get {
                return this.destinationField;
            }
            set {
                if ((object.ReferenceEquals(this.destinationField, value) != true)) {
                    this.destinationField = value;
                    this.RaisePropertyChanged("destination");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double distance {
            get {
                return this.distanceField;
            }
            set {
                if ((this.distanceField.Equals(value) != true)) {
                    this.distanceField = value;
                    this.RaisePropertyChanged("distance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double duration {
            get {
                return this.durationField;
            }
            set {
                if ((this.durationField.Equals(value) != true)) {
                    this.durationField = value;
                    this.RaisePropertyChanged("duration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string instructions {
            get {
                return this.instructionsField;
            }
            set {
                if ((object.ReferenceEquals(this.instructionsField, value) != true)) {
                    this.instructionsField = value;
                    this.RaisePropertyChanged("instructions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.ServiceReference1.Location source {
            get {
                return this.sourceField;
            }
            set {
                if ((object.ReferenceEquals(this.sourceField, value) != true)) {
                    this.sourceField = value;
                    this.RaisePropertyChanged("source");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string transportMode {
            get {
                return this.transportModeField;
            }
            set {
                if ((object.ReferenceEquals(this.transportModeField, value) != true)) {
                    this.transportModeField = value;
                    this.RaisePropertyChanged("transportMode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VelibStation", Namespace="http://schemas.datacontract.org/2004/07/velibPlanner")]
    [System.SerializableAttribute()]
    public partial class VelibStation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int availableVehiclesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int freeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.ServiceReference1.Location locationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int numberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int availableVehicles {
            get {
                return this.availableVehiclesField;
            }
            set {
                if ((this.availableVehiclesField.Equals(value) != true)) {
                    this.availableVehiclesField = value;
                    this.RaisePropertyChanged("availableVehicles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int free {
            get {
                return this.freeField;
            }
            set {
                if ((this.freeField.Equals(value) != true)) {
                    this.freeField = value;
                    this.RaisePropertyChanged("free");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.ServiceReference1.Location location {
            get {
                return this.locationField;
            }
            set {
                if ((object.ReferenceEquals(this.locationField, value) != true)) {
                    this.locationField = value;
                    this.RaisePropertyChanged("location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int number {
            get {
                return this.numberField;
            }
            set {
                if ((this.numberField.Equals(value) != true)) {
                    this.numberField = value;
                    this.RaisePropertyChanged("number");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IVelibPlannerService")]
    public interface IVelibPlannerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibPlannerService/ComputeRoute", ReplyAction="http://tempuri.org/IVelibPlannerService/ComputeRouteResponse")]
        Client.ServiceReference1.Route ComputeRoute(Client.ServiceReference1.Location current, Client.ServiceReference1.Location destination);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibPlannerService/ComputeRoute", ReplyAction="http://tempuri.org/IVelibPlannerService/ComputeRouteResponse")]
        System.Threading.Tasks.Task<Client.ServiceReference1.Route> ComputeRouteAsync(Client.ServiceReference1.Location current, Client.ServiceReference1.Location destination);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibPlannerService/anotherRoute", ReplyAction="http://tempuri.org/IVelibPlannerService/anotherRouteResponse")]
        Client.ServiceReference1.Route anotherRoute();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibPlannerService/anotherRoute", ReplyAction="http://tempuri.org/IVelibPlannerService/anotherRouteResponse")]
        System.Threading.Tasks.Task<Client.ServiceReference1.Route> anotherRouteAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibPlannerService/getNearestVelibStation", ReplyAction="http://tempuri.org/IVelibPlannerService/getNearestVelibStationResponse")]
        Client.ServiceReference1.VelibStation getNearestVelibStation(Client.ServiceReference1.Location l);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibPlannerService/getNearestVelibStation", ReplyAction="http://tempuri.org/IVelibPlannerService/getNearestVelibStationResponse")]
        System.Threading.Tasks.Task<Client.ServiceReference1.VelibStation> getNearestVelibStationAsync(Client.ServiceReference1.Location l);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVelibPlannerServiceChannel : Client.ServiceReference1.IVelibPlannerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VelibPlannerServiceClient : System.ServiceModel.ClientBase<Client.ServiceReference1.IVelibPlannerService>, Client.ServiceReference1.IVelibPlannerService {
        
        public VelibPlannerServiceClient() {
        }
        
        public VelibPlannerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VelibPlannerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VelibPlannerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VelibPlannerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Client.ServiceReference1.Route ComputeRoute(Client.ServiceReference1.Location current, Client.ServiceReference1.Location destination) {
            return base.Channel.ComputeRoute(current, destination);
        }
        
        public System.Threading.Tasks.Task<Client.ServiceReference1.Route> ComputeRouteAsync(Client.ServiceReference1.Location current, Client.ServiceReference1.Location destination) {
            return base.Channel.ComputeRouteAsync(current, destination);
        }
        
        public Client.ServiceReference1.Route anotherRoute() {
            return base.Channel.anotherRoute();
        }
        
        public System.Threading.Tasks.Task<Client.ServiceReference1.Route> anotherRouteAsync() {
            return base.Channel.anotherRouteAsync();
        }
        
        public Client.ServiceReference1.VelibStation getNearestVelibStation(Client.ServiceReference1.Location l) {
            return base.Channel.getNearestVelibStation(l);
        }
        
        public System.Threading.Tasks.Task<Client.ServiceReference1.VelibStation> getNearestVelibStationAsync(Client.ServiceReference1.Location l) {
            return base.Channel.getNearestVelibStationAsync(l);
        }
    }
}
