//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IVelibPlannerService")]
    public interface IVelibPlannerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibPlannerService/ComputeRoute", ReplyAction="http://tempuri.org/IVelibPlannerService/ComputeRouteResponse")]
        velibPlanner.Route ComputeRoute(velibPlanner.Location current, velibPlanner.Location destination);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibPlannerService/ComputeRoute", ReplyAction="http://tempuri.org/IVelibPlannerService/ComputeRouteResponse")]
        System.Threading.Tasks.Task<velibPlanner.Route> ComputeRouteAsync(velibPlanner.Location current, velibPlanner.Location destination);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVelibPlannerServiceChannel : ConsoleApp1.ServiceReference1.IVelibPlannerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VelibPlannerServiceClient : System.ServiceModel.ClientBase<ConsoleApp1.ServiceReference1.IVelibPlannerService>, ConsoleApp1.ServiceReference1.IVelibPlannerService {
        
        public VelibPlannerServiceClient() {
        }
        
        public VelibPlannerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VelibPlannerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VelibPlannerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VelibPlannerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public velibPlanner.Route ComputeRoute(velibPlanner.Location current, velibPlanner.Location destination) {
            return base.Channel.ComputeRoute(current, destination);
        }
        
        public System.Threading.Tasks.Task<velibPlanner.Route> ComputeRouteAsync(velibPlanner.Location current, velibPlanner.Location destination) {
            return base.Channel.ComputeRouteAsync(current, destination);
        }
    }
}
